[package]
name = "sample_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
diesel = { version = "2.2.3", features = ["r2d2", "sqlite", "returning_clauses_for_sqlite_3_35"] }
log = "0.4.22"
pretty_env_logger = "0.5.0"
serde = { version = "1.0.209", features = ["derive"] }
